# Generated by Django 3.2 on 2022-11-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='imgSrc',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
