# Generated by Django 3.2 on 2022-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0002_alter_employee_imgsrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='imgSrc',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
